// Representative review catalogue, shared by mobile and desktop.
// The production implementation will need a complete localized Unicode catalogue.
const groups = [
  ['faces', 'Смайлы', '😀 улыбка smile|😃 радость happy|😄 счастье happy|😁 сиять grin|😆 смех laugh|😅 пот sweat|😂 смех laugh|🤣 смех rofl|🥲 слеза tear|☺️ улыбка smile|😊 улыбка blush|😇 ангел angel|🙂 улыбка smile|🙃 перевернутый upside down|😉 подмигивание wink|😌 облегчение relieved|😍 любовь love|🥰 любовь love|😘 поцелуй kiss|😗 поцелуй kiss|😋 вкусно yum|😛 язык tongue|😜 подмигивание wink|🤪 безумие crazy|😎 круто cool|🤩 восторг star|🥳 праздник party|😏 ухмылка smirk|😒 недовольство unamused|😞 грусть sad|😔 грусть sad|😟 тревога worry|😕 сомнение confused|🙁 грусть sad|☹️ грусть sad|😣 упорство persevere|😖 растерянность confounded|😫 усталость tired|😩 усталость tired|🥺 просьба please|😭 плач cry|😤 злость angry|😠 злость angry|😡 злость rage|🤯 взрыв mind blown|😳 смущение flushed|🥵 жара hot|🥶 холод cold|😱 страх scream|😨 страх fear|😮 удивление wow|😯 удивление hush|😲 удивление astonished|😴 сон sleep|🤔 думать think|🫡 честь salute|🤗 объятия hug|🤭 хихикать giggle|🫣 подглядывать peek|🤫 тихо hush|🤐 молчать zip|🤨 сомнение suspicious|😐 нейтральный neutral|🙄 глаза roll|🤥 ложь lie|😬 неловкость awkward|🤒 болеть sick|🤧 чих sneeze|🤢 тошнота sick|🤮 тошнота vomit|🤖 робот robot|👻 призрак ghost'],
  ['people', 'Люди и жесты', '👍 лайк спасибо thumbs up|👎 дизлайк thumbs down|👌 хорошо ok|🤌 жест pinch|🤏 немного small|✌️ мир peace|🤞 удача luck|🤟 любовь love|🤘 рок rock|🤙 звонок call|👈 влево left|👉 вправо right|👆 вверх up|👇 вниз down|☝️ внимание point|✋ стоп stop|🤚 рука hand|🖐️ пять hand|🖖 привет vulcan|👋 привет wave|🤝 договор handshake|👏 аплодисменты clap|🙌 ура hooray|🫶 любовь heart hands|🙏 спасибо thanks pray|💪 сила strong|🦾 сила robot arm|🤷 непонятно shrug|🤦 facepalm|🙋 вопрос question|🙇 поклон bow|👩 женщина woman|👨 мужчина man|👶 ребенок baby|🧑 человек person|👀 глаза eyes|🧠 мозг brain|🫀 сердце heart|👂 ухо ear|👣 следы feet'],
  ['nature', 'Животные и природа', '🐶 собака dog|🐱 кот cat|🐭 мышь mouse|🐹 хомяк hamster|🐰 кролик rabbit|🦊 лиса fox|🐻 медведь bear|🐼 панда panda|🐨 коала koala|🐯 тигр tiger|🦁 лев lion|🐮 корова cow|🐷 свинья pig|🐸 лягушка frog|🐵 обезьяна monkey|🐔 курица chicken|🐧 пингвин penguin|🐦 птица bird|🦆 утка duck|🦅 орел eagle|🦉 сова owl|🦋 бабочка butterfly|🐝 пчела bee|🐢 черепаха turtle|🐬 дельфин dolphin|🐳 кит whale|🌸 цветок flower|🌹 роза rose|🌻 подсолнух sunflower|🌳 дерево tree|🌵 кактус cactus|🍀 удача clover|🍁 осень leaf|☀️ солнце sun|🌙 луна moon|⭐ звезда star|🌈 радуга rainbow|🔥 огонь fire|❄️ снег snow|🌊 волна wave'],
  ['food', 'Еда и напитки', '🍏 яблоко apple|🍎 яблоко apple|🍐 груша pear|🍊 апельсин orange|🍋 лимон lemon|🍌 банан banana|🍉 арбуз watermelon|🍇 виноград grape|🍓 клубника strawberry|🫐 черника blueberry|🍒 вишня cherry|🍑 персик peach|🥭 манго mango|🍍 ананас pineapple|🥑 авокадо avocado|🥦 брокколи broccoli|🥕 морковь carrot|🌽 кукуруза corn|🍞 хлеб bread|🥐 круассан croissant|🧀 сыр cheese|🍕 пицца pizza|🍔 бургер burger|🍟 картофель fries|🍣 суши sushi|🍜 лапша noodles|🍰 торт cake|🎂 день рождения birthday|🍩 пончик donut|🍪 печенье cookie|🍫 шоколад chocolate|🍬 конфета candy|☕ кофе coffee|🍵 чай tea|🥤 напиток drink|🧋 чай bubble tea|🧃 сок juice|🥛 молоко milk|🍿 попкорн popcorn|🍦 мороженое ice cream'],
  ['activity', 'Спорт и праздники', '⚽ футбол football|🏀 баскетбол basketball|🏈 football|⚾ бейсбол baseball|🎾 теннис tennis|🏐 волейбол volleyball|🏓 пинг понг table tennis|🏸 бадминтон badminton|🥊 бокс boxing|🎯 цель target|🏆 победа trophy|🥇 первое место medal|🥈 второе место medal|🥉 третье место medal|🎖️ медаль medal|🎉 праздник party|🎊 конфетти confetti|🎈 шар balloon|🎁 подарок gift|🎀 бант ribbon|🎄 елка christmas|🎃 тыква halloween|🎮 игра game|🎲 кубик dice|🧩 пазл puzzle|🎨 искусство art|🎬 кино movie|🎤 микрофон music|🎧 музыка headphones|🎸 гитара guitar|🎹 пианино piano|🎺 труба trumpet'],
  ['travel', 'Путешествия', '🚗 машина car|🚕 такси taxi|🚌 автобус bus|🚎 троллейбус trolley|🚓 полиция police|🚑 скорая ambulance|🚒 пожарная fire engine|🚲 велосипед bike|🚂 поезд train|🚆 поезд train|✈️ самолет plane|🚀 ракета rocket|🛸 нло ufo|🚁 вертолет helicopter|⛵ лодка sailboat|🚢 корабль ship|🏠 дом home|🏢 офис office|🏙️ город city|🏔️ горы mountain|🏖️ пляж beach|🏕️ кемпинг camping|🗺️ карта map|🧭 компас compass'],
  ['objects', 'Предметы', '💡 идея light bulb|💻 компьютер laptop|🖥️ монитор monitor|📱 телефон phone|⌚ часы watch|📷 камера camera|📺 телевизор tv|🔋 батарея battery|🔌 питание plug|📚 книги books|📖 книга book|✏️ карандаш pencil|🖊️ ручка pen|📝 заметка memo|📌 закреп pin|📎 скрепка clip|💼 работа briefcase|📅 календарь calendar|🔑 ключ key|🔒 замок lock|🔔 колокол bell|📣 объявление announcement|🛠️ инструмент tools|⚙️ настройки gear'],
  ['symbols', 'Символы', '❤️ любовь сердце heart love|🧡 сердце orange heart|💛 сердце yellow heart|💚 сердце green heart|💙 сердце blue heart|💜 сердце purple heart|🖤 сердце black heart|🤍 сердце white heart|🤎 сердце brown heart|💔 разбитое сердце broken heart|💕 сердца love|💖 любовь sparkle heart|💗 любовь growing heart|💘 любовь cupid|💝 подарок gift heart|💯 сто hundred|✨ блеск sparkles|💥 взрыв boom|💫 звезда dizzy|💤 сон sleep|✅ готово done check|❌ нет cross|❗ важно important|❓ вопрос question|⚠️ внимание warning|♻️ переработка recycle|➕ плюс plus|➖ минус minus|🔴 красный red|🟠 оранжевый orange|🟡 желтый yellow|🟢 зеленый green|🔵 синий blue|🟣 фиолетовый purple|⚫ черный black|⚪ белый white'],
  ['flags', 'Флаги', '🏳️ флаг white flag|🏴 флаг black flag|🏁 финиш finish|🚩 флаг red flag|🇰🇿 казахстан kazakhstan|🇷🇺 россия russia|🇬🇧 великобритания uk|🇺🇸 сша usa|🇫🇷 франция france|🇩🇪 германия germany|🇮🇹 италия italy|🇪🇸 испания spain|🇹🇷 турция turkey|🇯🇵 япония japan|🇰🇷 корея korea|🇨🇳 китай china'],
];
export const categories = groups.map(([id, title, rows]) => ({ id, title, items: rows.split('|').map(row => { const [emoji, ...words] = row.split(' '); return { emoji, name: words.join(' ') }; }) }));
export const allEmoji = categories.flatMap(group => group.items);
